'use client';

import { useEffect, useState } from 'react';

const qaPairs = [
  {
    question: 'Does the supplier have documented sterilization validation?',
    answer:
      'Yes, the supplier maintains sterilization validation protocols in compliance with ISO 11135 and CFR §820.75.',
  },
  {
    question: 'Are training records maintained for critical processes?',
    answer:
      'Training records are available and updated quarterly as per CFR §820.25 and ISO 13485 guidelines.',
  },
  {
    question: 'Has the supplier completed a recent internal audit?',
    answer:
      'An internal audit was conducted in Q1 2024, covering all critical processes as outlined in ISO 13485.',
  },
];

export default function AutoGeneratedResponses() {
  const [qaList, setQaList] = useState<typeof qaPairs>([]);
  const [loadingIndex, setLoadingIndex] = useState<number | null>(0);

  useEffect(() => {
    if (loadingIndex === null) return;

    if (loadingIndex < qaPairs.length) {
      const timer = setTimeout(() => {
        setQaList((prev) => [...prev, qaPairs[loadingIndex]]);
        setLoadingIndex((i) => (i !== null ? i + 1 : null));
      }, 500);

      return () => clearTimeout(timer);
    } else {
      setLoadingIndex(null);
    }
  }, [loadingIndex]);

  return (
    <div className='bg-white border rounded-lg p-6 shadow-md w-full h-full min-h-[20rem] text-gray-900 overflow-hidden'>
      <h3 className='text-gray-600 text-sm font-semibold mb-4'>
        Auto-Generated Audit Responses
      </h3>
      <div className='space-y-4'>
        {qaList.map((item, index) => (
          <div key={index} className='text-sm'>
            <p className='font-semibold'>
              {index + 1}. {item.question}
            </p>
            <p className='text-gray-700 mt-1 italic'>{item.answer}</p>
          </div>
        ))}
      </div>
      {loadingIndex !== null && (
        <div className='mt-6 flex flex-col items-center'>
          <div className='w-10 h-10 border-4 border-gray-300 border-t-gray-600 rounded-full animate-spin'></div>
          <p className='text-sm text-gray-600 mt-3'>
            Generating response {loadingIndex + 1} of {qaPairs.length}...
          </p>
        </div>
      )}
    </div>
  );
}
