'use client';

import { useEffect, useState } from 'react';

const questionList = [
  'Does the supplier have documented sterilization validation?',
  'Are training records maintained for critical processes?',
  'Has the supplier completed a recent internal audit?',
  'Are incoming materials verified upon receipt?',
  'Is there a CAPA process for nonconforming products?',
];

export default function AutoGeneratedQuestions() {
  const [questions, setQuestions] = useState<string[]>([]);
  const [loadingIndex, setLoadingIndex] = useState<number | null>(0);

  useEffect(() => {
    if (loadingIndex === null) return;

    if (loadingIndex < questionList.length) {
      const timer = setTimeout(() => {
        setQuestions((prev) => [...prev, questionList[loadingIndex]]);
        setLoadingIndex((i) => (i !== null ? i + 1 : null));
      }, 500);

      return () => clearTimeout(timer);
    } else {
      setLoadingIndex(null);
    }
  }, [loadingIndex]);

  return (
    <div className='bg-white border rounded-lg p-6 shadow-md w-full h-full min-h-[20rem] text-gray-900 overflow-hidden'>
      <h3 className='text-gray-600 text-sm font-semibold mb-4'>
        Auto-Generated Audit Questions
      </h3>
      <div className='space-y-3'>
        {questions.map((q, index) => (
          <p key={index} className='text-sm font-medium'>
            {index + 1}. {q}
          </p>
        ))}
      </div>
      {loadingIndex !== null && (
        <div className='mt-6 flex flex-col items-center'>
          <div className='w-10 h-10 border-4 border-gray-300 border-t-gray-600 rounded-full animate-spin'></div>
          <p className='text-sm text-gray-600 mt-3'>
            Generating question {loadingIndex + 1} of {questionList.length}...
          </p>
        </div>
      )}
    </div>
  );
}
