/* eslint-disable @typescript-eslint/no-unused-vars */
'use client';

import { LinkedInLogoIcon } from '@radix-ui/react-icons';
import { useState, useRef, useEffect } from 'react';
import Image from 'next/image';
import { motion, AnimatePresence } from 'framer-motion';
import VerticalBarGraph from './components/VerticalBarGraph';
import AutoGeneratedQuestions from './components/AutoGeneratedQuestions';
import AutoGeneratedResponses from './components/AutoGeneratedResponses';

const rotatingComponents = [
  <VerticalBarGraph key='bar' />,
  <AutoGeneratedQuestions key='questions' />,
  <AutoGeneratedResponses key='responses' />,
];

export default function HomePage() {
  useEffect(() => {
    const header = document.getElementById('main-header');
    let lastScrollY = window.scrollY;

    const handleScroll = () => {
      const currentY = window.scrollY;

      if (header) {
        if (currentY > 40 && !header.classList.contains('scrolled')) {
          header.classList.add('scrolled');
        } else if (currentY <= 10 && header.classList.contains('scrolled')) {
          header.classList.remove('scrolled');
        }
      }

      lastScrollY = currentY;
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const formRef = useRef<HTMLDivElement>(null);
  const scrollToForm = () =>
    formRef.current?.scrollIntoView({ behavior: 'smooth' });

  const [formData, setFormData] = useState({ email: '', company: '' });
  const [loading, setLoading] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [index, setIndex] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setIndex((prev) => (prev + 1) % rotatingComponents.length);
    }, 4000);
    return () => clearInterval(interval);
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const res = await fetch('/api/contact', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });

      if (res.ok) {
        setSubmitted(true);
        setFormData({ email: '', company: '' });
      } else {
        alert('Something went wrong.');
      }
    } catch (err) {
      console.error(err);
      alert('Failed to submit.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className='min-h-screen flex flex-col text-white bg-gray-800'>
      {/* Header */}
      <header
        id='main-header'
        className='sticky top-0 z-50 flex justify-between items-center px-6 lg:px-16 py-2 bg-gray-800 shadow-md transition-all duration-300'
      >
        <Image
          src='/AiDit-logo-v1.jpg'
          alt='AiDit Logo'
          width={220}
          height={70}
          className='transition-all duration-300 ease-in-out lg:sticky-logo shrink-on-scroll'
        />
        <button
          onClick={scrollToForm}
          className='bg-orange-600 hover:bg-orange-500 text-white font-semibold py-2 px-4 rounded-lg'
        >
          Book Demo
        </button>
      </header>

      {/* Top Section */}
      <section className='flex flex-col lg:flex-row px-6 lg:px-16 py-20 gap-6 lg:gap-[10rem] items-center justify-center bg-gray-500 relative overflow-hidden'>
        <div className='absolute inset-0 bg-gray-500 bg-opacity-80 z-0' />

        {/* Content */}
        <div className='relative z-10 max-w-2xl'>
          <h1 className='text-4xl font-extrabold mb-6 leading-tight'>
            AI Integrated Data Intelligence Tool
          </h1>
          <p className='text-lg font-semibold mb-6 leading-tight text-gray-200'>
            An AI-driven platform for audit automation, analysis, and compliance
            intelligence, with data privacy at its core.
          </p>
          <ul className='space-y-5 text-lg'>
            {[
              {
                title: 'Answer External Audits Instantly',
                description:
                  'Quickly locate relevant documentation and generate compliant responses.',
              },
              {
                title: 'Identify Nonconformities in Real Time',
                description:
                  'Surface gaps and issues across your Quality System before they become audit findings.',
              },
              {
                title: 'Automate Supplier & Internal Audits',
                description:
                  'Generate tailored audit questions based on training documents and standards.',
              },
              {
                title: 'Monitor Risk Through Continuous Analytics',
                description:
                  'Gain organization-wide insight into documentation health and audit readiness.',
              },
            ].map((item, idx) => (
              <li key={idx} className='flex items-start gap-3'>
                <span className='text-green-400 mt-1'>✔</span>
                <div>
                  <p className='font-semibold text-white leading-snug'>
                    {item.title}
                  </p>
                  <p className='text-sm text-gray-300 leading-snug'>
                    {item.description}
                  </p>
                </div>
              </li>
            ))}
          </ul>
        </div>

        {/* Rotating Component */}
        <div className='relative z-10 w-full lg:w-1/3 h-64 lg:h-96'>
          <AnimatePresence mode='wait'>
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.5 }}
              className='w-full h-full'
            >
              {rotatingComponents[index]}
            </motion.div>
          </AnimatePresence>
        </div>
      </section>

      {/* Value Props Section */}
      <section className='bg-gray-800 px-6 lg:px-16 py-10'>
        <div className='max-w-6xl mx-auto'>
          <h2 className='text-3xl font-bold text-white mb-10 text-center'>
            How Ai.Dit Can Help Your Organization
          </h2>
          <div className='grid grid-cols-1 lg:grid-cols-2 gap-6'>
            {[
              {
                icon: '/icon-1-dk-resources.png',
                title: "Reclaim Up to 30% of Your Team's Resources",
                bullets: [
                  'Free up staff by automating audit prep and document review.',
                  'Focus your team on high-risk areas instead of repetitive compliance tasks.',
                ],
              },
              {
                icon: '/icon-1-dk-time.png',
                title: 'Cut Audit Prep & Onboarding Time by Over 60%',
                bullets: [
                  'Ai.Dit surfaces relevant documentation instantly, speeding up audit prep and internal reviews.',
                  'New team members can self-serve SOPs and key data, reducing training time and ramp-up effort.',
                ],
              },
              {
                icon: '/icon-1-dk-quality.png',
                title: 'Reduce Nonconformities by 40% with Smart Oversight',
                bullets: [
                  'Leverage our HITL-enhanced AI to ensure consistent, high-quality audit responses.',
                  'Catch issues early through continuous data validation and document quality checks.',
                ],
              },
              {
                icon: '/icon-1-dk-cost.png',
                title: 'Lower Compliance Costs by 25% Through Automation',
                bullets: [
                  'Replace costly manual processes with intelligent workflows.',
                  'Avoid unnecessary expenses by catching documentation gaps early.',
                ],
              },
              {
                icon: '/icon-1-dk-efficiency.png',
                title:
                  'Boost Compliance Efficiency by 55% Across Critical Pipelines',
                bullets: [
                  'Get ahead of issues with real-time alerts and AI-powered nonconformity detection.',
                  'Benefit from evolving AI that adapts to your workflow logic and regulatory standards.',
                  'Centralize documentation access and cut search time organization-wide with intelligent, context-aware retrieval.',
                ],
              },
            ].map((item, idx) => (
              <div
                key={idx}
                className='bg-white text-gray-900 p-6 rounded-lg shadow-md flex flex-col gap-4 h-full'
              >
                <div className='flex items-center gap-4'>
                  <Image
                    src={item.icon}
                    alt={item.title}
                    width={90}
                    height={90}
                  />
                  <h3 className='text-lg font-bold'>{item.title}</h3>
                </div>
                <ul className='list-disc list-inside text-sm pl-2'>
                  {item.bullets.map((point, i) => (
                    <li key={i} className='text-gray-700'>
                      {point}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Form Section */}
      <section ref={formRef} className='bg-gray-600 px-6 lg:px-16 pt-10 pb-20'>
        <div className='max-w-3xl mx-auto text-center'>
          <h2 className='text-3xl font-bold mb-3'>
            Your <span className='font-medium italic'>Audits Simplified!</span>
          </h2>
          <p className='text-2xl font-bold mb-6'>
            Get Early Access & Book a Demo
          </p>
          {submitted ? (
            <p className='text-green-400 text-xl'>
              Thanks! We&apos;ll be in touch soon.
            </p>
          ) : (
            <form onSubmit={handleSubmit} className='space-y-6'>
              <input
                type='email'
                name='email'
                placeholder='Work Email'
                value={formData.email}
                onChange={(e) =>
                  setFormData({ ...formData, email: e.target.value })
                }
                className='w-full px-4 py-3 rounded-md text-black'
                required
              />
              <input
                type='text'
                name='company'
                placeholder='Company Name'
                value={formData.company}
                onChange={(e) =>
                  setFormData({ ...formData, company: e.target.value })
                }
                className='w-full px-4 py-3 rounded-md text-black'
                required
              />
              <button
                type='submit'
                className='w-full bg-orange-600 hover:bg-orange-500 text-white font-semibold py-3 px-6 rounded-lg disabled:bg-gray-300 disabled:text-gray-500'
                disabled={loading}
              >
                {loading ? 'Sending...' : 'Book Demo'}
              </button>
            </form>
          )}
        </div>
      </section>

      {/* Footer */}
      <footer className='bg-gray-800 px-6 lg:px-16 py-6 border-t border-gray-700'>
        <div className='flex flex-col md:flex-row justify-between items-center gap-4'>
          <p className='text-sm text-gray-400'>
            &copy; {new Date().getFullYear()} Ardor Life All rights reserved.
          </p>
          <div className='flex gap-4 text-gray-400'>
            <a
              href='#'
              target='_blank'
              aria-label='LinkedIn'
              rel='noopener noreferrer'
            >
              <LinkedInLogoIcon className='w-5 h-5 hover:text-white' />
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}
