/* eslint-disable @typescript-eslint/no-unused-vars */
'use client';

import { useState, useRef, useEffect } from 'react';
import Image from 'next/image';
import { motion, AnimatePresence } from 'framer-motion';
import VerticalBarGraph from './components/VerticalBarGraph';
import AutoGeneratedQuestions from './components/AutoGeneratedQuestions';
import AutoGeneratedResponses from './components/AutoGeneratedResponses';
import Header from './components/Header';
import Footer from './components/Footer';

const rotatingComponents = [
  <AutoGeneratedQuestions key='questions' />,
  <VerticalBarGraph key='bar' />,
  <AutoGeneratedResponses key='responses' />,
];

export default function HomePage() {
  useEffect(() => {
    const header = document.getElementById('main-header');
    let lastScrollY = window.scrollY;

    const handleScroll = () => {
      const currentY = window.scrollY;

      if (header) {
        if (currentY > 40 && !header.classList.contains('scrolled')) {
          header.classList.add('scrolled');
        } else if (currentY <= 10 && header.classList.contains('scrolled')) {
          header.classList.remove('scrolled');
        }
      }

      lastScrollY = currentY;
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const formRef = useRef<HTMLDivElement>(null);
  const scrollToForm = () =>
    formRef.current?.scrollIntoView({ behavior: 'smooth' });

  const [formData, setFormData] = useState({ email: '', company: '' });
  const [loading, setLoading] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [index, setIndex] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setIndex((prev) => (prev + 1) % rotatingComponents.length);
    }, 4000);
    return () => clearInterval(interval);
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const res = await fetch('/api/contact', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });

      if (res.ok) {
        setSubmitted(true);
        setFormData({ email: '', company: '' });
      } else {
        alert('Something went wrong.');
      }
    } catch (err) {
      console.error(err);
      alert('Failed to submit.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className='min-h-screen flex flex-col text-white bg-gray-800'>
      <Header scrollToForm={scrollToForm} />

      {/* Top Section */}
      <section className='pt-64 flex flex-col lg:flex-row px-6 lg:px-16 py-48 gap-6 lg:gap-[10rem] items-center justify-center relative overflow-hidden'>
        <div
          className='absolute inset-0 z-0 bg-cover bg-no-repeat bg-center filter blur-[2px] scale-100'
          style={{
            // backgroundImage: "url('/aidit-bg.png')",
            // backgroundImage: "url('/tech-pattern.jpg')",
            backgroundImage: "url('/ai-bg.jpg')",
            backgroundPosition: 'top center',
          }}
        />

        <div className='absolute inset-0 bg-blue-900 bg-opacity-80 z-0' />

        {/* Content */}
        <div className='relative z-10 max-w-2xl'>
          <h1 className='text-4xl font-extrabold mb-6 leading-tight'>
            AI Integrated Data Intelligence Tool
          </h1>
          <p className='text-lg font-semibold mb-6 leading-tight text-gray-200'>
            An AI-driven platform for audit automation, analysis, and compliance
            intelligence, with data privacy at its core.
          </p>
          <ul className='space-y-5 text-lg'>
            {[
              {
                title: 'Answer Customer and Agency Audits Instantly',
                description:
                  'Quickly locate relevant documentation and generate compliant responses.',
              },
              {
                title: 'Identify Nonconformities in Real Time',
                description:
                  'Surface gaps and issues across your Quality System before they become audit findings.',
              },
              {
                title: 'Automate Supplier & Internal Audits',
                description:
                  'Generate tailored audit questions based on quality system requirements and standards.',
              },
              {
                title: 'Monitor Risk Through Continuous Analytics',
                description:
                  'Gain organization-wide insight into quality system health and audit readiness.',
              },
            ].map((item, idx) => (
              <li key={idx} className='flex items-start gap-3'>
                <span className='text-green-400 mt-1'>✔</span>
                <div>
                  <p className='font-semibold text-white leading-snug'>
                    {item.title}
                  </p>
                  <p className='text-sm text-gray-300 leading-snug'>
                    {item.description}
                  </p>
                </div>
              </li>
            ))}
          </ul>
        </div>

        {/* Rotating Component */}
        <div className='relative z-10 w-full lg:w-1/3 h-64 lg:h-96'>
          <AnimatePresence mode='wait'>
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.5 }}
              className='w-full h-full'
            >
              {rotatingComponents[index]}
            </motion.div>
          </AnimatePresence>
        </div>
      </section>

      {/* Value Props Section */}
      <section className='bg-gray-800 px-6 lg:px-16 py-10 border-t border-b border-gray-500'>
        <div className='max-w-6xl mx-auto'>
          <h2 className='text-3xl font-bold text-white mb-10 text-center'>
            How Ai.Dit Can Help Your Organization
          </h2>
          <div className='grid grid-cols-1 lg:grid-cols-2 gap-6'>
            {[
              {
                icon: '/icon-1-dk-resources.png',
                title: "Reclaim Up to 30% of Your Team's Resources",
                bullets: [
                  'Free up staff by automating audit prep and document review.',
                  'Focus your team on high-risk areas instead of repetitive compliance tasks.',
                ],
              },
              {
                icon: '/icon-1-dk-time.png',
                title: 'Cut Audit Prep & Onboarding Time by Over 60%',
                bullets: [
                  'Ai.Dit surfaces relevant documentation instantly, speeding up audit prep and internal reviews.',
                  'New team members can self-serve SOPs and key data, reducing training time and ramp-up effort.',
                ],
              },
              {
                icon: '/icon-1-dk-quality.png',
                title: 'Reduce Nonconformities by 60% with Smart Oversight',
                bullets: [
                  'Leverage our HITL-enhanced AI to ensure consistent, high-quality audit responses.',
                  'Catch issues early through continuous data validation and document quality checks.',
                ],
              },
              {
                icon: '/icon-1-dk-cost.png',
                title: 'Lower Compliance Costs by 60% Through Automation',
                bullets: [
                  'Replace costly manual processes with intelligent workflows.',
                  'Avoid unnecessary expenses by catching documentation gaps early.',
                ],
              },
              {
                icon: '/icon-1-dk-efficiency.png',
                title:
                  'Boost Compliance Efficiency by 70% Across Critical Pipelines',
                bullets: [
                  'Get ahead of issues with real-time alerts and AI-powered nonconformity detection.',
                  'Benefit from evolving AI that adapts to your workflow logic and regulatory standards.',
                  'Centralize documentation access and cut search time organization-wide with intelligent, context-aware retrieval.',
                ],
              },
            ].map((item, idx) => (
              <div
                key={idx}
                className='bg-white text-gray-900 p-6 rounded-lg shadow-md flex flex-col gap-4 h-full'
              >
                <div className='flex items-center gap-4'>
                  <Image
                    src={item.icon}
                    alt={item.title}
                    width={90}
                    height={90}
                  />
                  <h3 className='text-lg font-bold'>{item.title}</h3>
                  <sup className='ml-1 text-xs text-gray-500'>[{idx + 1}]</sup>
                </div>
                <ul className='list-disc list-inside text-sm pl-2'>
                  {item.bullets.map((point, i) => (
                    <li key={i} className='text-gray-700'>
                      {point}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
            <div className='mt-12 text-xs text-gray-200'>
              <p className='mb-1 font-semibold'>Sources:</p>
              <ol className='list-decimal list-inside space-y-1'>
                <li>
                  Harvard Business Review – “How to Maximize AI ROI webinar”
                  (2025).{' '}
                  <a
                    href='https://www.nice.com/lps/rpcs-hbr?utm_campaign=NL_Q225_EN_PLT_GLOB_250831_ODW_RPCS-HBR-ROI-AI-Process-MGMT&utm_source=meta&utm_medium=cpc&utm_content=0367529&utm_detail=dentsu-lal-glob&fbclid=IwZXh0bgNhZW0BMABhZGlkAaseYJpYvPgBHoifKFClrtOod1xpsUY6wh3gGRErtORzRwJonLmZ4Nxmj3BdNLw5frqXwF7r_aem_5OpWPhdCE-Eg3O13obiZGw&utm_id=120215616744490616&utm_term=120223214891220616'
                    className='underline text-gray-300'
                    target='_blank'
                    rel='noopener noreferrer'
                  >
                    View summary
                  </a>
                </li>
                <li>
                  Number Analytics – “AI Compliance Monitoring Impact Report”
                  (2023).{' '}
                  <a
                    href='https://www.numberanalytics.com/blog/ai-compliance-monitoring-firms'
                    className='underline text-gray-300'
                    target='_blank'
                    rel='noopener noreferrer'
                  >
                    View report
                  </a>
                </li>
                <li>
                  Hyperproof – “Compliance Automation Survey” (2023).{' '}
                  <a
                    href='https://hyperproof.io/resource/compliance-automation/'
                    className='underline text-gray-300'
                    target='_blank'
                    rel='noopener noreferrer'
                  >
                    Read more
                  </a>
                </li>
                <li>
                  ResearchGate – “AI-Driven Compliance Audits for Enhanced
                  Efficiency” (2024).{' '}
                  <a
                    href='https://www.researchgate.net/publication/378490586_Augmenting_the_Watchdog_AI_-Driven_Compliance_Audits_for_Enhanced_Efficiency_and_Accuracy'
                    className='underline text-gray-300'
                    target='_blank'
                    rel='noopener noreferrer'
                  >
                    View study
                  </a>
                </li>
                <li>
                  Concur – “Improving Expense Report Audits with AI” (2023).{' '}
                  <a
                    href='https://www.concur.com/blog/article/people-ai-automation-how-to-improve-expense-report-audit'
                    className='underline text-gray-300'
                    target='_blank'
                    rel='noopener noreferrer'
                  >
                    Visit source
                  </a>
                </li>
                <li>
                  ResearchGate – “AI-Driven Compliance Audits for Enhanced
                  Efficiency” (2024).{' '}
                  <a
                    href='https://www.researchgate.net/publication/378490586_Augmenting_the_Watchdog_AI_-Driven_Compliance_Audits_for_Enhanced_Efficiency_and_Accuracy'
                    className='underline text-gray-300'
                    target='_blank'
                    rel='noopener noreferrer'
                  >
                    View study
                  </a>
                </li>
              </ol>
            </div>
          </div>
        </div>
      </section>

      {/* Form Section */}
      <section ref={formRef} id='demo' className='relative overflow-hidden'>
        {/* Blurred Background Image */}
        <div
          className='absolute inset-0 bg-cover bg-center filter blur-[3px] scale-105 z-0'
          style={{ backgroundImage: "url('/tech-pattern.jpg')" }}
        />

        {/* Blue overlay */}
        <div className='absolute inset-0 bg-blue-700 bg-opacity-70 z-10' />

        {/* Form Content */}
        <div className='relative z-20 px-6 lg:px-16 pt-16 pb-24 max-w-3xl mx-auto text-center'>
          <h2 className='text-3xl font-bold mb-3'>
            Your <span className='font-medium italic'>Audits Simplified!</span>
          </h2>
          <p className='text-2xl font-bold mb-6'>
            Get Early Access & Book a Demo
          </p>

          {submitted ? (
            <p className='text-green-400 text-xl'>
              Thanks! We&apos;ll be in touch soon.
            </p>
          ) : (
            <form onSubmit={handleSubmit} className='space-y-6'>
              <input
                type='email'
                name='email'
                placeholder='Company Email'
                value={formData.email}
                onChange={(e) =>
                  setFormData({ ...formData, email: e.target.value })
                }
                className='w-full px-4 py-3 rounded-sm text-black'
                required
              />
              <input
                type='text'
                name='company'
                placeholder='Company Name'
                value={formData.company}
                onChange={(e) =>
                  setFormData({ ...formData, company: e.target.value })
                }
                className='w-full px-4 py-3 rounded-sm text-black'
                required
              />
              <button
                type='submit'
                className='w-full bg-orange-600 hover:bg-orange-500 text-white font-semibold py-3 px-6 rounded-sm disabled:bg-gray-300 disabled:text-gray-500'
                disabled={loading}
              >
                {loading ? 'Sending...' : 'Book Demo'}
              </button>
            </form>
          )}
        </div>
      </section>

      <Footer />
    </div>
  );
}
